# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: clone
      run: git clone https://github.com/GuGuYeah/Uranium.git

    # Runs a set of commands using the runners shell
    - name: gradle
      run:  git submodule update --init --recursive

    # Runs a set of commands using the runners shell
    - name: gradle2
      run:   gradle clean setupCauldron jar api packageLibraries
        echo Add other actions to build,
        echo test, and deploy your project.
